
deployment:
  tasks:
    - export DEPLOYPATH=/home/whiztech/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R Learing_System/Learing_System/ClientApp/build/* $DEPLOYPATH
